# Generated by Django 3.2.5 on 2021-07-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0005_alter_qna_qnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='imageUrl',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
