# Generated by Django 3.2.5 on 2021-07-09 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0007_alter_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='qna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qna.qna'),
        ),
    ]
