# Generated by Django 3.2.5 on 2021-07-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0008_comment_qna'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
